# Generated by Django 5.2 on 2025-05-08 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('URL', 'URL'), ('File', 'File'), ('Email', 'Email')], max_length=10)),
                ('item', models.CharField(max_length=255)),
                ('result', models.CharField(choices=[('Clean', 'Clean'), ('Malware', 'Malware'), ('Phishing', 'Phishing')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
